I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    define s = connect()
  File "game/script.rpy", line 28, in script
    define s = connect()
  File "game/script.rpy", line 28, in <module>
    define s = connect()
  File "game/script.rpy", line 12, in connect
    s.connect((HOST, PORT))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\watto\Downloads\renpy\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\watto\Downloads\renpy\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 28, in script
    define s = connect()
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/script.rpy", line 28, in script
    define s = connect()
  File "C:\Users\watto\Downloads\renpy\renpy-8.0.3-sdk\renpy\ast.py", line 2441, in execute
    self.set()
  File "C:\Users\watto\Downloads\renpy\renpy-8.0.3-sdk\renpy\ast.py", line 2455, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\watto\Downloads\renpy\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 28, in <module>
    define s = connect()
  File "game/script.rpy", line 12, in connect
    s.connect((HOST, PORT))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Windows-10-10.0.22623 AMD64
Ren'Py 8.0.3.22090809
NatamTV 1.0
Tue Oct 11 22:05:31 2022
